"""add_current_plans_table

Revision ID: 6cbd27420b4d
Revises: 56a223a64930
Create Date: 2025-08-01 01:15:11.944379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cbd27420b4d'
down_revision = '56a223a64930'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create PaymentStatus enum if it doesn't exist
    from sqlalchemy.dialects import postgresql
    paymentstatus_enum = postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='paymentstatus')
    paymentstatus_enum.create(op.get_bind(), checkfirst=True)
    
    # Create current_plans table
    op.create_table('current_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('investment_amount', sa.Float(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current_plans')
    # ### end Alembic commands ###
